id: P007938
initial_creation_type: ocr
source_metadata:
  id: bdr:W23745
  title: ཆོས་འབྱུང་ངོ་མཚར་རྒྱ་མཚོ།
  author: ''
  volumes:
    4c547cbd16044ea2a27ab702b2577b51:
      image_group_id: I2578
      title: ''
      volume_number: 1
      total_pages: 776
      base_file: v001.txt
    6cefae699c364d6c88aab4d191ae7d4b:
      image_group_id: I2579
      title: ''
      volume_number: 2
      total_pages: 792
      base_file: v002.txt
ebook_metadata:
  title: ཆོས་འབྱུང་ངོ་མཚར་རྒྱ་མཚོ།
  author: ''
  sku: P007938
  cover: cover.jpg
  layers:
  - pagination
